#!/usr/bin/env python3
"""Regenerate (or drift-check) every committed fixture from its seeder.

Walks ``ca_elevation_engine.registry.SCENARIOS``, loads each seeder module from
``engine/fixtures/seeders/<scenario>.py`` BY FILE PATH (``fixtures/`` is not a
package on ``sys.path``), and (re)produces the committed manifest, capture, and
golden for that scenario from the seeder's ``build_manifest()`` /
``build_capture()`` plus the engine pipeline. Deterministic: no clocks, no
randomness (the golden clock is the fixed ``GENERATED_AT``).

The byte layout of every file is fixed by a single serializer here:
    * manifest + capture -> authored key order, indent=2, NO trailing newline
                            (matches the committed synthetic corpus exactly).
    * golden             -> the engine's own ``render_json(report) + "\\n"``
                            (sorted keys, indent=2, trailing newline) -- the
                            exact function that produced the committed goldens.

Committed paths come from the registry (the single source of truth for stems and
golden filenames):
    synthetic/<SCENARIO_PAYLOAD_STEMS[scenario]>.manifest.json
    synthetic/<SCENARIO_PAYLOAD_STEMS[scenario]>.capture.json
    golden/<SCENARIO_GOLDENS[scenario]>

Modes:
    (default)        rewrite the committed fixtures in place.
    --check          DO NOT write; regenerate in memory and byte-diff against the
                     committed files. Exit 1 (with a unified diff to stderr) on
                     any drift. This is the CI / pre-push guard.

Options:
    --fixtures-root DIR   committed-fixtures root to compare/write against
                          (default: REPO_ROOT/engine/fixtures). Lets tests target
                          a tmp copy.
    -v / --verbose

Exit codes:
    0  all fixtures regenerated (or, with --check, all match)
    1  --check found drift, a seeder/registry inconsistency, or the engine import
       failed (regen runs the pipeline; install with ``pip install -e engine``)
"""

from __future__ import annotations

import argparse
import difflib
import importlib
import importlib.util
import json
import sys
import tempfile
from pathlib import Path
from types import ModuleType

REPO_ROOT = Path(__file__).resolve().parents[2]
SEEDERS_DIR = REPO_ROOT / "engine" / "fixtures" / "seeders"
FIXTURES_ROOT = REPO_ROOT / "engine" / "fixtures"  # default committed root


def _seeder_module(scenario: str) -> ModuleType:
    """Load the seeder module for ``scenario`` from ``SEEDERS_DIR``.

    Seeders in this corpus come in two shapes: f01 imports the engine absolutely
    and is self-contained, while f02-f07 use a package-relative ``from . import
    _common``. To support both, we ensure ``engine/`` is importable and load via
    the real ``fixtures.seeders.<scenario>`` package so relative imports resolve;
    we fall back to a by-file-path load (sufficient for self-contained seeders).
    Fails with a clear message (exit 1 via SystemExit) if the file is missing --
    mirrors test_registry's file-exists assertion.
    """
    path = SEEDERS_DIR / f"{scenario}.py"
    if not path.exists():
        raise SystemExit(f"seeder not found for scenario {scenario!r}: {path}")

    engine_root = REPO_ROOT / "engine"
    if str(engine_root) not in sys.path:
        sys.path.insert(0, str(engine_root))
    try:
        return importlib.import_module(f"fixtures.seeders.{scenario}")
    except ImportError:
        pass  # fall back to a by-file-path load (self-contained seeders)

    spec = importlib.util.spec_from_file_location(f"_seeder_{scenario}", path)
    if spec is None or spec.loader is None:  # pragma: no cover - defensive
        raise SystemExit(f"could not load seeder spec for scenario {scenario!r}: {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _authored_bytes(obj: dict) -> bytes:
    """Authored-order serialization (manifest, capture): indent=2, NO newline.

    Matches the committed synthetic corpus byte-for-byte (both f01's seeder and
    the ``_common.write_payloads`` helper used by f02+ serialize this way).
    """
    return json.dumps(obj, indent=2).encode("utf-8")


def _golden_bytes(report) -> bytes:
    """Engine-canonical serialization (golden)."""
    from ca_elevation_engine.report.json_report import render_json

    return (render_json(report) + "\n").encode("utf-8")


def _produce(scenario: str) -> dict[Path, bytes]:
    """Return committed-relative-path -> regenerated bytes for one scenario."""
    from ca_elevation_engine import registry
    from ca_elevation_engine.pipeline import run_pipeline

    mod = _seeder_module(scenario)
    stem = registry.SCENARIO_PAYLOAD_STEMS[scenario]
    golden_name = registry.SCENARIO_GOLDENS[scenario]

    manifest = mod.build_manifest()
    capture = mod.build_capture()
    manifest_bytes = _authored_bytes(manifest)
    capture_bytes = _authored_bytes(capture)

    # Derive the golden from the real pipeline on these exact payloads, stamped
    # with the seeder's fixed clock. Ingest validates the payloads against the
    # schemas, so a malformed seeder fails here.
    generated_at = getattr(mod, "GENERATED_AT", None)
    if generated_at is None:
        from fixtures.seeders import _common as _c  # type: ignore[import-not-found]

        generated_at = _c.GENERATED_AT

    with tempfile.TemporaryDirectory() as td:
        tdp = Path(td)
        (tdp / "m.manifest.json").write_bytes(manifest_bytes)
        (tdp / "c.capture.json").write_bytes(capture_bytes)
        result = run_pipeline(
            tdp / "m.manifest.json",
            tdp / "c.capture.json",
            generated_at=generated_at,
        )
    golden_bytes = _golden_bytes(result.report)

    return {
        Path("synthetic") / f"{stem}.manifest.json": manifest_bytes,
        Path("synthetic") / f"{stem}.capture.json": capture_bytes,
        Path("golden") / golden_name: golden_bytes,
    }


def regenerate(
    scenario: str,
    *,
    check: bool,
    fixtures_root: Path = FIXTURES_ROOT,
    verbose: bool = False,
) -> list[str]:
    """Regenerate (or drift-check) one scenario's committed fixtures.

    In ``check`` mode: return a list of human-readable drift messages (one per
    drifted-or-missing committed file), empty when clean. Do not write.
    In write mode: write regenerated bytes onto the committed paths; return [].
    """
    produced = _produce(scenario)
    drift: list[str] = []

    for rel, new_bytes in produced.items():
        committed = fixtures_root / rel
        if check:
            if not committed.exists():
                drift.append(f"{scenario}: committed fixture missing: {rel}")
                continue
            old_bytes = committed.read_bytes()
            if old_bytes != new_bytes:
                drift.append(f"{scenario}: drift in {rel}")
                if verbose:
                    print(f"  DRIFT: {rel}")
            elif verbose:
                print(f"  OK: {rel}")
        else:
            committed.parent.mkdir(parents=True, exist_ok=True)
            committed.write_bytes(new_bytes)
            if verbose:
                print(f"  wrote: {rel}")

    return drift


def _unified(scenario: str, rel: Path, committed: Path, new_bytes: bytes) -> str:
    if committed.exists():
        old_text = committed.read_text(encoding="utf-8").splitlines(keepends=True)
    else:
        old_text = []
    new_text = new_bytes.decode("utf-8").splitlines(keepends=True)
    diff = difflib.unified_diff(
        old_text,
        new_text,
        fromfile=f"committed/{rel}",
        tofile=f"regenerated/{rel}",
    )
    return "".join(diff)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; diff committed fixtures against the seeders (CI guard)",
    )
    parser.add_argument(
        "--fixtures-root",
        type=Path,
        default=FIXTURES_ROOT,
        help="committed-fixtures root to compare/write against",
    )
    parser.add_argument("-v", "--verbose", action="store_true", help="print each file checked")
    args = parser.parse_args(argv)

    try:
        from ca_elevation_engine import registry
    except ImportError:
        print("ERROR: install the engine first: pip install -e engine", file=sys.stderr)
        return 1

    written = 0
    messages: list[str] = []
    try:
        for scenario in registry.SCENARIOS:
            produced = _produce(scenario)
            for rel, new_bytes in produced.items():
                committed = args.fixtures_root / rel
                if args.check:
                    if not committed.exists() or committed.read_bytes() != new_bytes:
                        messages.append(f"{scenario}: drift/missing in {rel}")
                        sys.stderr.write(_unified(scenario, rel, committed, new_bytes))
                    elif args.verbose:
                        print(f"  OK: {rel}")
                else:
                    committed.parent.mkdir(parents=True, exist_ok=True)
                    committed.write_bytes(new_bytes)
                    written += 1
                    if args.verbose:
                        print(f"  wrote: {rel}")
    except ImportError:
        print("ERROR: install the engine first: pip install -e engine", file=sys.stderr)
        return 1

    if args.check:
        if messages:
            print(
                f"\nFAILED: {len(messages)} fixture(s) drifted from their seeders:",
                file=sys.stderr,
            )
            for m in messages:
                print(f"  - {m}", file=sys.stderr)
            return 1
        print("Fixtures up to date.")
        return 0

    print(f"Regenerated {written} file(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
