"""Heavy E57 test: a REAL E57 container through the production loader + pipeline.

Exercises the highest-risk, lowest-coverage code in the registration item -- the
``pye57`` E57 read path (``pointcloud._load_e57``) -- against a genuine,
committed E57 fixture (``fixtures/scanner/f08_posed_scan.e57``) generated by
``tools/make_e57_fixture.py``. It proves:

1. The production loader (:func:`ca_elevation_engine.pointcloud.load_point_cloud`)
   reads a real E57 and returns the *pose-applied global* coordinates -- i.e. it
   honours the E57 coordinate/scaling/pose conventions, not just an identity-pose
   happy path. The fixture's scan carries a non-trivial 90-deg-about-Z rotation
   and a large translation; if the loader skipped the pose, the assertion fails.
2. That E57, fed end-to-end through ``run_pipeline`` as a shot's ``point_cloud``,
   drives ICP and surfaces the residual note in the verdict report.

No module-level ``pytestmark``: tests are marked only ``heavy`` and SKIP cleanly
when ``pye57`` (read) / ``open3d`` (ICP) are absent.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

import numpy as np
import pytest

from ca_elevation_engine import pointcloud as pc
from ca_elevation_engine.models import CapturePackage, Observation, Point3
from ca_elevation_engine.pipeline import run_pipeline

ENGINE_ROOT = Path(__file__).resolve().parents[1]
FIXTURE_REL = "scanner/f08_posed_scan.e57"
FIXTURE_ABS = ENGINE_ROOT / "fixtures" / FIXTURE_REL
BUNDLE_DIR = ENGINE_ROOT / "fixtures"


def _load_generator():
    """Load the fixture generator module by path (single source of geometry truth).

    Loaded via importlib (matching the repo's tool-test pattern) so we don't rely
    on ``tools`` being an importable package. Importing it needs only numpy +
    engine (pye57 is imported lazily inside ``main``), so it is safe even when the
    heavy backend is absent.
    """
    path = ENGINE_ROOT / "tools" / "make_e57_fixture.py"
    spec = importlib.util.spec_from_file_location("make_e57_fixture", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_e57_fixture_is_committed():
    """Guard: the binary fixture is actually present (it is a committed artifact)."""
    assert FIXTURE_ABS.exists(), (
        f"missing E57 fixture {FIXTURE_ABS}; regenerate with "
        "`python -m tools.make_e57_fixture` (needs the [heavy] extra)"
    )


@pytest.mark.heavy
def test_loader_reads_real_e57_with_pose_applied():
    """The production loader returns pose-applied global coords from a real E57."""
    pytest.importorskip("pye57")
    gen = _load_generator()
    expected_global = gen.arkit_frame_cloud()

    pts = pc.load_point_cloud(FIXTURE_REL, str(BUNDLE_DIR))

    assert pts.dtype == np.float64
    assert pts.shape == expected_global.shape
    assert np.isfinite(pts).all()
    # Pose + scaling honoured: matches the known ARKit-frame (global) cloud within
    # E57's scaled-integer quantization (~1e-6 here), NOT the raw local coords.
    assert np.abs(pts - expected_global).max() < 1e-4
    # Sanity that the pose was actually applied: the stored LOCAL points are a
    # rotated/translated copy, so the loaded global cloud must NOT coincide with
    # the local one (a loader that ignored the pose would fail this).
    rot = _rotation_about_z(gen.E57_ROTATION_DEG)
    local = (rot.T @ (expected_global - gen.E57_TRANSLATION).T).T
    assert np.abs(pts - local).max() > 1.0


def _rotation_about_z(deg: float) -> np.ndarray:
    r = np.deg2rad(deg)
    c, s = np.cos(r), np.sin(r)
    return np.array([[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]])


@pytest.mark.heavy
def test_e57_end_to_end_register_to_verdict():
    """Real E57 -> coarse+ICP register -> verdict report, residual note surfaced."""
    pytest.importorskip("pye57")
    pytest.importorskip("open3d")
    gen = _load_generator()

    manifest = gen.build_manifest()
    shot = gen.build_shot()
    # Match the device so its DeviceResult carries the matched shot's ICP notes.
    shot.observations = [Observation(position=Point3(*gen.DEVICE_POS))]
    capture = CapturePackage(schema_version="1.0.0", project_id=manifest.project.id, shots=[shot])

    result = run_pipeline(
        manifest,
        capture,
        bundle_dir=str(BUNDLE_DIR),
        generated_at="2026-06-29T00:00:00Z",
    )
    (dr,) = result.report.device_results
    assert dr.verdict.value == "pass"
    icp_notes = [n for n in dr.notes if "ICP refinement applied" in n]
    assert icp_notes, f"E57 ICP residual note missing: {dr.notes}"
    assert icp_notes[0].startswith("registration: ")
